twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        project_name: '%env(project_name)%'
        project_url: '%env(project_url)%'